version: "3"
services:
  ignite:
    image: apacheignite/ignite:2.13.0
    environment:
      - JVM_OPTS=-Xms512m -Xmx512m -server -XX:+AggressiveOpts -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
    expose:
      - 10800
    networks:
      - ignite
    ports:
      - 10800:10800  
networks:
  ignite:
    driver: bridge